### ISSUE TITLE
Linkout to other sources (CIRCE, ATLAS, PubMed)

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Penelope#13]

**Comment by pbr6cornell** [comment]
Priorities within this:

1..  Link-out to CIRCE from Observatioal Evidence tab, so that if you click on a cohort, you can open up new window to see how the cohort was defined,.
1.  Link-out to PubMed from literature tab:  nice-to-have, if it makes it easier to go from count of articles to list of articles
2.  Link-out to ATLAS  - lowest priorities, optional nice-to-have
