### ISSUE TITLE
ACHILLES webAPI calls seem slower than HERACLES calls

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Penelope#34]
Can we make sure we have ACHILLES_results indexed appropriately

**Comment by pbr6cornell** [comment]
I added indexes to ACHILLES tables, and now everything's pretty fast

**Comment by anthonysena** [comment]
Was just looking into this as well based on a note that @leeevans made on the WebAPI issue list:

https://github.com/OHDSI/WebAPI/issues/66

Was looking at the indicies and saw that your indexing analysis_id and stratum_1 on ACHILLES_result. We may want to consider another index that includes stratum_2 since that is also used in the getDrugEraPrevalenceByGenderAgeYear.sql query: https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/getDrugEraPrevalenceByGenderAgeYear.sql
